config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf import settings
from django.views import defaults as default_views






urlpatterns = [

    # Utils
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

# Translition
prefix_default_language = False
urlpatterns += i18n_patterns(

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),

    # User management
    path("Accounts/", include("smbh_website.users.urls", namespace="Users"),),
    path("Accounts/", include("allauth.urls")),
    # OAuth 2
    path('Users/API/OAuth/', include('oauth2_provider.urls', namespace='oauth2_provider')),

    # My Apps
    path('', include('app.urls', namespace='App')),
    path('Blog/', include('blog.urls', namespace='Blog')),

)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

smbh_website/app/urls.py
from django.urls import path, include, re_path

from .views import (HomeView,
    ContactView,
    PortfolioView,
    PortfolioDetailView
	)

# NameSpace
app_name = 'App'


urlpatterns = [

    path('', HomeView.as_view(), name='home'),
    path('Contact', ContactView.as_view(), name='contact'),
    path('Portfolio', PortfolioView.as_view(), name='portfolio'),
    path('Portfolio/<slug:slug>', PortfolioDetailView.as_view(), name='gallery'),
    # path('Login', auth_views.login, {'template_name': 'registration/Login.html'}, name='login'),
    # path('Login', auth_views.LoginView, name='login'),
    # path('Logout', auth_views.LogoutView, name='logout'),


    # DRF API
    path('API/', include('app.api.urls')),

]

smbh_website/blog/urls.py
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from .views import (BlogView, post_detail, PostCreateView, PostUpdateView, CommentThreadView, comment_delete)




# For Manage NameSpace
app_name = 'Blog'


urlpatterns = [

    path('', BlogView.as_view(), name='blog'),
    # path('<slug:slug>', PostDetailView.as_view(), name='post'),


    # DRF API
    path('API/', include('blog.api.urls')),

    # Comment
    path('<int:id>/Delete', comment_delete, name='delete'),
    path('<int:id>', CommentThreadView.as_view(), name='thread'),
    # Post
    path('Create', PostCreateView.as_view(), name='post_create'),
    path('<slug>/Update', PostUpdateView.as_view(), name='post_update'),
    path('<slug>', post_detail, name='post'),

]

smbh_website/users/urls.py
from django.urls import path, include

from users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view
)

# from django.contrib.auth.views import LoginView, LogoutView


app_name = "Users"

urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("Redirect/", view=user_redirect_view, name="redirect"),
    path("<slug:username>/Update", user_update_view, name="update"),
    path("<slug:username>", user_detail_view, name="detail"),

    # path('Login/', LoginView.as_view(), name='login'),
    # path('Logout/', LogoutView.as_view(), name='logout'),


    # DRF API
    path('API/', include('users.api.urls')),
]

smbh_website/app/forms.py
from django import forms
# from django.contrib import admin
from .models import Contact



class ContactForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'cols': 30, 'rows': 6}))
    # content = forms.CharField(widget=forms.Textarea(attrs={'cols': 30, 'rows': 6, 'class': 'form-control'}))
    # slug = CharField(validators=[validate_slug])
    # my_secret = forms.CharField(widget=forms.TextInput(attrs={'autocomplete': 'off'}))
    # my_secret = forms.CharField(widget=forms.PasswordInput())

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass

    # def clean(self):
    #     cleaned_data = super(ContactForm, self).clean()
    #     name = cleaned_data.get('name')
    #     email = cleaned_data.get('email')
    #     phone
    #     if phone ....
    #     subject = cleaned_data.get('subject')
    #     content = cleaned_data.get('content')
    #


    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'email', 'phone', 'subject', 'content')
        widgets = {
            # 'content': forms.Textarea(attrs={'cols': 140, 'rows': 60}),
        }

        # field_classes = {
        #     'slug': MySlugFormField,
        # }
        # labels = {
        #     'name': _('Writer'),
        # }
        # help_texts = {
        #     'name': _('Some useful help text.'),
        # }
        # error_messages = {
        #     'name': {
        #         'max_length': _("This writer's name is too long."),
        #     },
        # }

smbh_website/app/templates/contact_individual.html
{% extends "base_smbh.html" %} {% block title %} Contact Me | smbh {% endblock title %} {% load static %} {% load i18n %}
{% block style %}

<!-- Customize -->
<link rel="stylesheet" href="{% static 'css/contact.css' %}" /> {% endblock style %} {% block script %}

<!-- Customize -->
<script src="{% static 'js/contact.js' %}"></script>

{% endblock script %} {% block content %}


<div class="gallery-parallax Image-Container" id="Contact-image">

  <!-- NAVBAR -->
  <div class="container" id="NavContainer">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

      {% comment %} Brand {% endcomment %}

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link waves-light" href="{% url 'App:home' %}">{% trans 'Home' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-light" href="{% url 'App:home' %}">{% trans 'Services' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-light" href="{% url 'Blog:blog' %}">{% trans 'Blog' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-light" href="{% url 'App:portfolio' %}">{% trans 'Portfolio' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-light active" href="{% url 'App:contact' %}">{% trans 'Contact' %}</a>
          </li>
        </ul>

        {% comment %}
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> {% endcomment %}


      </div>

      <strong>
        <a class="navbar-brand mr-auto" href="{% url 'App:home' %}">SMB
          <span style="color:royalblue;">H</span>
        </a>
      </strong>

    </nav>
  </div>


  <!-- Contact -->
  <section class="my-5" id="contact">


    <!-- Form row -->
    <div class="row col-lg-12 col-md-12 col-sm-12">

      <!-- Form container -->
      <div class="col-lg-6 col-md-12 col-sm-12 mb-4">

        <!-- Form  -->
        <form class="card" id="contact-form" method="post">
          {% csrf_token %}
          <div class="card-body">
            <!-- Header -->
            <div class="form-header accent-1">
              <h3 class="mt-2">
                <i class="material-icons md-24 mt-4 blue-text">
                  mail_outline
                </i> Write to Me:</h3>
            </div>
            <p class="dark-grey-text">We'll write rarely, but only the best content.</p>

            <!-- Messages -->
            {% if messages %}
            <ul class="messages alert alert-info">
              {% for message in messages %}
              <li id="message_{{ forloop.counter }}" {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                {{ message }}
              </li>
              {% endfor %}
            </ul>
            {% endif %}

            <!-- Errors -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
              {% for err in form.errors %} {{ err }} {% endfor %}
            </div>
            {% endif %}
            {% comment %}
            <!-- Name -->
            <div class="md-form">
              <input type="text" id="id_first_name" class="form-control" name="first_name" maxlength='100' autocomplete="off" required />
              <label for="id_first_name">
                <span>
                  <i class="fa fa-user grey-text"></i>
                </span> Name *
              </label>
            </div>
            <!-- Email -->
            <div class="md-form">
              <input type="email" id="id_email" class="form-control" name="email" maxlength='254' autocomplete="off" required />
              <label for="id_email">
                <span>
                  <i class="fa fa-envelope grey-text"></i>
                </span>Email *
              </label>
            </div>
            <!-- Phone -->
            <div class="md-form">
              <input type="text" id="id_phone" class="form-control" name="phone" maxlength='20' autocomplete="off" />
              <label for="id_phone">
                <span>
                  <i class="fa fa-mobile grey-text"></i>
                </span>Phone
              </label>
            </div>
            <!-- Subject -->
            <div class="md-form">
              <input type="text" id="id_ubject" class="form-control" name="subject" maxlength='100' autocomplete="off" required />
              <label for="id_ubject">
                <span>
                  <i class="fa fa-tag grey-text"></i>
                </span>Subject *
              </label>
            </div>
            <!-- Content -->
            <div class="md-form">
              <textarea type="text" id="id_content" class="form-control md-textarea" cols="30" rows="6" name="content" required></textarea>
              <label for="id_content">
                <span>
                  <i class="fa fa-comment" aria-hidden="true"></i>
                </span> Content *
              </label>
            </div> 
            {% endcomment %}
            {{ form.as_table }}

            <div class="text-center">
              <button class="btn btn-blue" type="submit">Send</button>
            </div>
          </div>
        </form>

      </div>


      <!-- Map container -->
      <div class="col-lg-6 col-md-12 col-sm-12">

        <!-- Google map-->
        <div id="Map" class="rounded z-depth-1-half map-container">

          <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d23054.49828412707!2d50.94513869495479!3d35.83122644286641!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2s!4v1532181565597"
            width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen></iframe>

        </div>
        <br>
        <!-- Buttons-->
        <div class="row text-center" id="Map-btn">
          <div class="col col-md-4 col-sm-4">
            <a class="btn-floating accent-1 rounded-circle">
              <i class="material-icons md-48 mt-4 blue-text">
                location_on
              </i>
            </a>
            <p class="mb-md-0">IR Iran, Tehran</p>
          </div>
          <div class="col col-md-4 col-sm-4">
            <a class="btn-floating accent-1 rounded-circle">
              <i class="material-icons md-36 mt-4 blue-text">
                perm_phone_msg
              </i>
            </a>
            <p></p>
            <p class="mb-md-0">9:00 - 21:00</p>
          </div>
          <div class="col col-md-4 col-sm-4">
            <a class="btn-floating accent-1 rounded-circle">
              <i class="material-icons md-36 mt-4 blue-text">
                mail_outline
              </i>
            </a>
            <p class="mb-0">SmbHop@gmail.com</p>
          </div>
        </div>

      </div>


    </div>
    <!-- Grid row -->

  </section>


</div>

<!-- Footer -->
{% block footer %}
<div class="page-footer font-small unique-color-dark pt-0" id="footer">
  <div class="footer-copyright py-3 text-center" style="color : #969696;">
    <span>© <span class="footer_logo">SMB </span>
      <span style="color:royalblue;">H</span>
      All rights reserved.
    </span>
  </div>
</div>
{% endblock footer %} {% endblock content %}

smbh_website/app/templates/home.html
{% extends "base_smbh.html" %} {% block title %} smbh | Home {% endblock title %} {% load static %} {% load i18n %}

<!-- Style Block -->
{% block style %}

<!-- Owl Carousel -->
<link rel="stylesheet" href="{% static 'Packages/OwlCarousel2-2.3.4/dist/assets/owl.carousel.min.css' %}" />
<link rel="stylesheet" href="{% static 'Packages/OwlCarousel2-2.3.4/dist/assets/owl.theme.default.min.css' %}" />

<!-- Customize -->
<link rel="stylesheet" href="{% static 'css/home.css' %}" /> {% endblock style %}


<!-- Script Block -->
{% block script %}

<!-- Owl Carousel -->
<script src="{% static 'Packages/OwlCarousel2-2.3.4/dist/owl.carousel.min.js' %}"></script>

<!-- Customize -->
<script src="{% static 'js/home.js' %}"></script>

{% endblock script %} {% block header %}

<!-- Intro -->
<div id="intro-section">

  <!-- NAVBAR -->
  <div class="container" id="NavContainer">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

      {% comment %} Brand {% endcomment %}

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link waves-light active" href="{% url 'App:home' %}">{% trans 'Home' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-light" href="#Services">{% trans 'Services' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-light" href="{% url 'Blog:blog' %}">{% trans 'Blog' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-light" href="{% url 'App:portfolio' %}">{% trans 'Portfolio' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-light" href="{% url 'App:contact' %}">{% trans 'Contact' %}</a>
          </li>
          {% comment %}
          <!-- Authentication -->
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'Users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
            </li>

            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
            </li>

          {% else %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
            </li>

            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
            </li>

          {% endif %}
          {% endcomment %}

        </ul>

        {% comment %} <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> {% endcomment %}


      </div>

      <strong>
        <a class="navbar-brand mr-auto" href="{% url 'App:home' %}">SMB
          <span style="color:royalblue;">H</span>
        </a>
      </strong>

    </nav>
  </div>


  <video class="gallery-parallax Image-Container" autoplay muted loop id="intro-video">
    <source src="{% static 'media/home_coding.mp4' %}" type="video/mp4" />
  </video>



  <!--title content-->
  <div class="Transition" id="intro-content">
    <div id="name">
      <strong>
        <p>Seyed Mohammad&nbsp;Bagher Hosseini</p>
      </strong>
    </div>

    <div id="def">
      <p>|&nbsp;Computer Software Engineer&nbsp;|</p>
    </div>
    <div id="Btn-AboutMe">
      <a class="btn btn-info btn-sm rounded" href="#AboutMe">{% trans 'About Me' %}</a>
    </div>
    <br/>
  </div>
  <div class="Image-Bottom-Center social">
    <div class="container">
      <ul>

        <a href="https://github.com/smb-h" target="_blank">
          <i class="fab fa-github"></i>
        </a>
        <a href="https://www.linkedin.com/in/smb-h-b64068155/" target="_blank">
          <i class="fab fa-linkedin-in"></i>
        </a>
        <a href="https://twitter.com/smb_h" target="_blank">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="https://t.me/smb_h/" target="_blank">
          <i class="fab fa-telegram-plane"></i>
        </a>

      </ul>
    </div>
  </div>
</div>

{% endblock header %}



<!-- Content -->

{% block content %}


<!-- About Me -->
<section class="jumbotron" id="AboutMe">
  <div>
    <div class="wow fadeIn" id="AboutMe-Head">
      <h1>{% trans 'About Me' %}</h1>
      <p>{% blocktrans %}

        {% endblocktrans %}
      </p>
    </div>
    <div class="row" id="AboutMe-Items-Container">
      <div class="col-sm AboutMe-Item wow fadeInUp">
        <h1>
          <i class="material-icons md-80" style="color: red;">bug_report</i>
        </h1>
        <h2>{% trans 'Experienced in' %}</h2>
        <p>
          Python, Django, MVT
          <br />Restful Api, API's
          <br/>JS, JQuery, Git
          <br/>SQL, PostgreSQL
          <br/>Design, Material, GUI, UI/UX
          </p>
      </div>
      <div class="col-sm AboutMe-Item wow fadeInUp" data-wow-delay="0.3s">
        <h1>
          <i class="material-icons md-80">info_outline</i>
        </h1>
        <h2>{% trans 'Familiar with' %}</h2>
        <p>
          MVC, C#, C, C++
          <br/>ReactJs, VueJs
          <br/>Bash, Linux, NginX
        </p>
      </div>
      <div class="col-sm AboutMe-Item wow fadeInUp" data-wow-delay="0.6s">
        <h1>
          <i class="material-icons md-80" style="color: rgb(75, 15, 15);">free_breakfast</i>
        </h1>
        <h2>{% trans 'Fun' %}</h2>
        <p>
          AI, Data Mining, Robotic
          <br/>IoT, Security, Technology, ...
          <br/>OpenSource &amp; FreeSoftware Community</p>
      </div>
    </div>


  </div>

</section>

<!-- Blog -->
<div class="card-deck" id="Blog">
  <!-- Latest Posts -->
  <div class="row col col-lg-12 col-md-12 col-sm-12">
    {% for post in LatestPost %} {% include "home_latest_post.html" %} {% endfor %}
  </div>

</div>



<!-- Services Carousel -->
<div class="gallery-parallax" id="Services">
  <div id="Services-Head">
    <p>{% trans 'SERVICES' %}</p>
    <h1> {% blocktrans %} What Can I Do For You? {% endblocktrans %}
    </h1>
  </div>
  <div class="owl-carousel owl-theme">
    <div class="Services-Item">
      <h1>
        <i class="material-icons md-80">devices_other</i>
      </h1>
      <h2>{% trans 'Develop' %}</h2>
      <p> {% blocktrans %} WebSite &amp; Application {% endblocktrans %} </p>
    </div>
    <div class="Services-Item">
      <h1>
        <i class="material-icons md-80">all_inclusive</i>
      </h1>
      <h2>{% trans 'Design' %}</h2>
      <p> {% blocktrans %} UI, UX, Graphic, Illustration {% endblocktrans %}</p>
    </div>
    <div class="Services-Item">
      <h1>
        <i class="material-icons md-80">public</i>
      </h1>
      <h2>{% trans 'Research' %}</h2>
      <p> {% blocktrans %} Technology, System, Security {% endblocktrans %} </p>
    </div>
    <div class="Services-Item">
      <h1>
        <i class="material-icons md-80">lightbulb_outline</i>
      </h1>
      <h2>{% trans 'Consultancy' %}</h2>
      <p> {% blocktrans %} E Commerce {% endblocktrans %} </p>
    </div>
    <div class="Services-Item">
      <h1>
        <i class="material-icons md-80">touch_app</i>
      </h1>
      <h2>{% trans 'Branding' %}</h2>
      <p></p>
    </div>
    <div class="Services-Item">
      <h1>
        <i class="material-icons md-80">timeline</i>
      </h1>
      <h2>{% trans 'Marketing' %}</h2>
      <p></p>
    </div>
  </div>
</div>


<!-- Footer -->
{% block footer %}
<div class="page-footer font-small unique-color-dark pt-0" id="footer">
  <div class="footer-copyright py-3 text-center" style="color : #969696;">
    <span>© <span class="footer_logo">SMB </span>
      <span style="color:royalblue;">H</span>
      All rights reserved.
    </span>
  </div>
</div>

{% endblock footer %}

{% endblock content %}

smbh_website/app/templates/home_latest_post.html
<div class="col col-lg-4 col-md-6 col-sm-12">
  <div class="card mb-4 Transition wow fadeInUp" data-wow-delay="0.1s">
    <!-- Featured image -->
    {% if post.image %}
    <div class="Image-Container view overlay">
      <img class="card-img-top Transition" src="{{ post.image.url }}" alt="{{ post.title }}" />
      <!-- Wave Mask -->
      <a>
        <div class="mask rgba-white-slight"></div>
      </a>

    </div>
    {% endif %}

    <div class="card-body">
      <center>
      <h3 class="card-title">
        <strong>{{ post.title }}</strong>
      </h3>
    </center>
      <p class="card-text">{{ post.summary | safe | truncatechars:256 }}</p>
      <div style="float: right;">
        <!-- Read more button -->
        <a class="btn btn-indigo btn-md" href="{% url 'Blog:post' slug=post.slug %}">Read more</a>
      </div>

      <!-- Tags -->
      <div class="row">
        {% for tag in post.tags.names %}
        <a style="color: royalblue;">
          <h6 class="font-weight-bold mb-3">

            <i class="pr-3">
              #{{ tag }}
            </i>

          </h6>
        </a>
        {% endfor %}
      </div>

    </div>
    <div class="card-footer">
      <small class="text-muted">
        <p>By
          <a>
            <strong> {{ post.author }} </strong>
          </a>, {{ post.publish }}</p>
      </small>
    </div>
  </div>
</div>

smbh_website/app/templates/portfolio.html
{% extends "base_smbh.html" %} {% block title %} Portfolio | smbh {% endblock title %}
<!---->
{% load static %} {% load i18n %} {% block style %}

<!-- Customize -->
<link rel="stylesheet" href="{% static 'css/blog.css' %}" />
<link rel="stylesheet" href="{% static 'css/portfolio.css' %}" /> {% endblock style %} {% block script %}

<!-- Customize -->
<!-- <script src="{% static 'js/portfolio.js' %}"></script> -->

{% endblock script %} {% block content %}


<div class="gallery-parallax Image-Container" id="Portfolio-image">

  <!-- NAVBAR -->
  <div class="container" id="NavContainer">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

      {% comment %} Brand {% endcomment %}

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link waves-light" href="{% url 'App:home' %}">{% trans 'Home' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-light" href="{% url 'App:home' %}">{% trans 'Services' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-light" href="{% url 'Blog:blog' %}">{% trans 'Blog' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-light active" href="{% url 'App:portfolio' %}">{% trans 'Portfolio' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-light" href="{% url 'App:contact' %}">{% trans 'Contact' %}</a>
          </li>
        </ul>

        {% comment %}
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> {% endcomment %}


      </div>

      <strong>
        <a class="navbar-brand mr-auto" href="{% url 'App:home' %}">SMB
          <span style="color:royalblue;">H</span>
        </a>
      </strong>

    </nav>
  </div>


  {% block PostList %}

  <!-- Blog -->
  <section class="my-5 container" id="blog">

    <!-- Posts -->
    <div class="card-deck">
      <div class="row col col-lg-12 col-md-12 col-sm-12">
        {% for post in Portfolio %} {% include "portfolio_post.html" %} {% endfor %}
      </div>
    </div>


  </section>


  <!-- Pagination -->
  {% if is_paginated %}
  <!--Pagination -->
  <nav aria-label="pagination" id="Paginator">
    <ul class="pagination pg-teal mb-0 justify-content-center">

      {% if page_obj.has_previous %}
      <!--First-->
      <li class="page-item">
        <a class="page-link" href="?page=1">First</a>
      </li>
      <!--Arrow left-->
      <li class="page-item">
        <a class="page-link" aria-label="Previous" href="?page={{ page_obj.previous_page_number }}">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %} {% for count in paginator.page_range %} {% if page_obj.number == count %}
      <li class="page-item active">
        <a class="page-link">{{ count }}
          <span class="sr-only">(current)</span>
        </a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="?page={{ count }}">{{ count }}</a>
      </li>
      {% endif %} {% endfor %} {% if page_obj.has_next %}
      <!--Arrow left-->
      <li class="page-item">
        <a class="page-link" aria-label="Previous" href="?page={{ page_obj.next_page_number }}">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      <!--Last-->
      <li class="page-item">
        <a class="page-link" href="?page=1">Last</a>
      </li>
      {% endif %}

    </ul>
  </nav>
  {% endif %} {% endblock PostList %}


</div>


<!-- Footer -->
{% block footer %}

<div class="page-footer font-small unique-color-dark pt-0" id="footer">
  <div class="footer-copyright py-3 text-center" style="color : #969696;">
    <span>© <span class="footer_logo">SMB </span>
      <span style="color:royalblue;">H</span>
      All rights reserved.
    </span>
  </div>
</div>

{% endblock footer %} {% endblock content %}

smbh_website/app/templates/react.html
{% extends "base.html" %}

{% block content %}
    

    <div id='reactify'></div>
    <!-- <div id='reactify2'></div> -->


{% endblock content %}